CREATE OR REPLACE PACKAGE BODY VALIDATE IS
	FUNCTION CPF(P_CPF IN VARCHAR2)
		RETURN BOOLEAN
	IS
		V_DIG_FIRST  NUMBER     := SUBSTR(P_CPF,10,1);
		V_DIG_SECOND NUMBER     := SUBSTR(P_CPF,11,1);
		V_SUM 		 NUMBER     := 0;
		V_TEMP       VARCHAR2(11);
	BEGIN
		FOR X IN 1 .. 10
		LOOP
			FOR Y IN 1 .. 11
			LOOP
				V_TEMP := V_TEMP||CHR(47+X);
			END LOOP;
			IF P_CPF = V_TEMP THEN
				RETURN FALSE;
			END IF;
		V_TEMP := '';
		END LOOP;
		FOR X IN 1 .. 9
		LOOP
			V_SUM := SUBSTR(P_CPF,X,1)*(11-X) + V_SUM;
		END LOOP;
		V_SUM := ((V_SUM * 10) MOD 11) MOD 10;
		IF V_SUM != V_DIG_FIRST THEN
			RETURN FALSE;
		ELSE
			V_SUM := 0;
			FOR X IN 1 .. 10
			LOOP
				V_SUM := SUBSTR(P_CPF,X,1)*(12-X) + V_SUM;
			END LOOP;
			V_SUM := ((V_SUM * 10) MOD 11) MOD 10;
			IF V_SUM != V_DIG_SECOND THEN
				RETURN FALSE;
			END IF;
		END IF;
		RETURN TRUE;
	END CPF;
END;